# Generated by Django 5.2.7 on 2025-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text="e.g., 'Web Developer' or 'Data Scientist'", max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
            options={
                'verbose_name_plural': 'Profile (Only one record needed)',
            },
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
