# Generated by Django 5.2.7 on 2025-10-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_remove_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Upload the certification badge or logo.', null=True, upload_to='certification_badges/')),
            ],
        ),
    ]
