# Generated by Django 5.2.7 on 2025-10-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='percentage_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
